export const ICON_COLOR = '#93C5FD';
export function makeGroup(label: string, icon: string, hex: string = ICON_COLOR, desc: string) {
    return { label, icon, color: hex, desc }
  }
  export const GROUPS_CONFIG = [
    makeGroup('Newsroom & Media',        'ti-news',             ICON_COLOR, 'News articles, press releases, events, and homepage highlights.'),
    makeGroup('Knowledge & Resources',   'ti-books',            ICON_COLOR, 'FAQs, publications, policies, consultations, and topic pages.'),
    makeGroup('Pages & Navigation',      'ti-layout-dashboard', ICON_COLOR, 'Main section pages, About Us, and quicklink directories.'),
    makeGroup('People & Organisation',   'ti-users',            ICON_COLOR, 'Staff profiles, management team, EC members, and contacts.'),
    makeGroup('Procurement & Licensing', 'ti-file-invoice',     ICON_COLOR, 'Job vacancies, tenders, quotations, and licensees.'),
    makeGroup('Location',                'ti-map-pin',          ICON_COLOR, 'ST office locations and contact details.'),
  ]
  
  export const CONTENT_TYPES = [
        { id:"newsroom", name:"Newsroom", machine:"newsroom", group:"Newsroom & Media", icon:"📰", color:"#FDE8E8",
          description:"The main content type for all news-related posts — press releases, events, announcements, workshops, ST statements, and media articles.",
          note:{kind:"tip",text:"Always set <strong>News Type</strong> and <strong>Publish Date</strong> — these are required for the post to appear in the right section."},
          taxonomyNote:"News Type controls where this post appears. Options: Press Releases, Announcement / Notice, ST Statements, ST@Media, Media Articles, Events, Workshops, News",
          fields:[
            {label:"Title",machine:"title",hint:"The headline of the article or announcement.",status:"required",type:"text"},
            {label:"Publish Date",machine:"field_publish_date",hint:"The official date shown as 'Issued' on the listing page.",status:"required",type:"date"},
            {label:"News Type",machine:"field_news_type",hint:"Pick a category (e.g. Events, Press Releases).",status:"required",type:"taxonomy"},
            {label:"Description",machine:"field_description",hint:"Short teaser text for listing cards.",status:"optional",type:"plain-text"},
            {label:"Content",machine:"field_content",hint:"Main body of the article.",status:"optional",type:"rich-text"},
            {label:"Featured Image",machine:"field_featured_image",hint:"Main image shown on listing cards.",status:"optional",type:"media-image"},
            {label:"File / Attachment",machine:"field_file",hint:"Attach a PDF.",status:"optional",type:"media-doc"},
            {label:"Location",machine:"field_location",hint:"For Events only — enter the venue or city.",status:"optional",type:"plain-text"},
            {label:"External Links",machine:"field_external_links",hint:"Link to an external source.",status:"optional",type:"link"},
            {label:"Featured",machine:"field_featured",hint:"Tick to feature this post as the hero card.",status:"optional",type:"boolean"},
            {label:"Tags",machine:"field_tags",hint:"Add tags to group related content.",status:"optional",type:"taxonomy",multiple:true},
          ]},
        { id:"highlights", name:"Highlights", machine:"highlights", group:"Newsroom & Media", icon:"⭐", color:"#FFF3E0",
          description:"Featured stories shown in the Highlights carousel on the homepage.",
          fields:[
            {label:"Title",machine:"title",hint:"Headline for the highlight card.",status:"required",type:"text"},
            {label:"Body",machine:"field_body",hint:"Main content.",status:"optional",type:"rich-text"},
            {label:"Featured Image",machine:"field_featured_image",hint:"Visual image shown on the highlight card.",status:"optional",type:"media-image"},
            {label:"Links",machine:"field_links",hint:"Call-to-action links. Multiple allowed.",status:"optional",type:"link",multiple:true},
            {label:"Tags",machine:"field_h_tags",hint:"Assign a Highlights Tag.",status:"optional",type:"taxonomy"},
          ]},
        { id:"faq", name:"FAQ", machine:"faq", group:"Knowledge & Resources", icon:"❓", color:"#E8F7EE",
          description:"Frequently asked questions. Each entry is a single question-and-answer pair.",
          note:{kind:"info",text:"<strong>FAQ Category</strong> and <strong>Topic Tag</strong> control how this FAQ is grouped on the FAQ page."},
          fields:[
            {label:"Title (Question)",machine:"title",hint:"Write as a full question.",status:"required",type:"text"},
            {label:"Answer",machine:"field_answers",hint:"The full answer.",status:"optional",type:"rich-text"},
            {label:"Question (Long)",machine:"field_question_long",hint:"Use when the question needs more context.",status:"optional",type:"plain-text"},
            {label:"Question with Images",machine:"field_question_with_images",hint:"Use when the question needs diagrams.",status:"optional",type:"rich-text"},
            {label:"FAQ Category",machine:"field_faq_category",hint:"Appears as filter tabs on the FAQ page.",status:"optional",type:"taxonomy",multiple:true},
            {label:"Topic Tag",machine:"field_topic_tag",hint:"Assigns this FAQ to a section.",status:"optional",type:"taxonomy"},
            {label:"Topic Reference",machine:"field_topic_reference",hint:"Link to a related Topic page.",status:"optional",type:"content-ref"},
            {label:"File Attachment",machine:"field_file_attachment",hint:"Attach supporting documents.",status:"optional",type:"media-doc",multiple:true},
            {label:"External Links",machine:"field_external_links",hint:"Link to an external resource.",status:"optional",type:"link"},
          ]},
        { id:"resource", name:"Resource", machine:"resource", group:"Knowledge & Resources", icon:"📄", color:"#EEF2F7",
          description:"Downloadable publications, reports, and magazines.",
          fields:[
            {label:"Title",machine:"title",hint:"Publication title.",status:"required",type:"text"},
            {label:"Summary",machine:"field_summary",hint:"Short description shown on listing cards.",status:"optional",type:"plain-text"},
            {label:"Resource Type",machine:"field_resource_type",hint:"Select the type (e.g. Magazine, Annual Report).",status:"optional",type:"taxonomy"},
            {label:"Publication Date",machine:"field_publication_date",hint:"The official date this resource was issued.",status:"optional",type:"date"},
            {label:"Cover Image",machine:"field_featured_image",hint:"Upload the cover thumbnail.",status:"optional",type:"media-image"},
            {label:"File",machine:"field_file",hint:"Upload the PDF for download.",status:"optional",type:"media-doc"},
            {label:"External Link",machine:"field_external_links",hint:"Use if the resource is hosted externally.",status:"optional",type:"link"},
            {label:"Topic Reference",machine:"field_topic_reference",hint:"Link to a related section/topic page.",status:"optional",type:"content-ref"},
          ]},
        { id:"policies", name:"Policies", machine:"policies", group:"Knowledge & Resources", icon:"📋", color:"#FDE8E8",
          description:"Official regulatory policies, guidelines, and frameworks.",
          fields:[
            {label:"Title",machine:"title",hint:"Name of the policy or guideline.",status:"required",type:"text"},
            {label:"Description",machine:"field_body",hint:"Full description or content.",status:"optional",type:"rich-text"},
            {label:"Policy Category",machine:"field_policy_categories",hint:"Assign to the relevant category.",status:"optional",type:"taxonomy"},
            {label:"Featured Image",machine:"field_featured_image",hint:"Optional cover image.",status:"optional",type:"media-image"},
            {label:"File Attachment",machine:"field_file_attachment",hint:"Attach the policy document(s).",status:"optional",type:"media-doc",multiple:true},
          ]},
        { id:"consultation_hub", name:"Consultation Hub", machine:"consultation_hub", group:"Knowledge & Resources", icon:"🤝", color:"#E8F7EE",
          description:"Public consultation documents and regulatory notices.",
          fields:[
            {label:"Title",machine:"title",hint:"Title of the consultation document.",status:"required",type:"text"},
            {label:"Body",machine:"field_body",hint:"Full content of the consultation.",status:"optional",type:"rich-text"},
            {label:"Key Documents",machine:"field_key_documents",hint:"Upload the consultation documents.",status:"optional",type:"media-doc",multiple:true},
          ]},
        { id:"topic", name:"Topic", machine:"topic", group:"Knowledge & Resources", icon:"🗂️", color:"#EEF2F7",
          description:"Sub-pages that sit under a main Page.",
          fields:[
            {label:"Title",machine:"title",hint:"Name of the topic.",status:"required",type:"text"},
            {label:"Introduction",machine:"field_introduction",hint:"Brief intro paragraph.",status:"optional",type:"plain-text"},
            {label:"Parent Page",machine:"field_parent",hint:"Link to the parent Page.",status:"optional",type:"content-ref"},
            {label:"File Attachment",machine:"field_file_attachment",hint:"Attach supporting documents.",status:"optional",type:"media-doc",multiple:true},
          ]},
        { id:"page", name:"Page", machine:"page", group:"Pages & Navigation", icon:"🖼️", color:"#F0EDE8",
          description:"Main section landing pages and standalone content pages.",
          note:{kind:"warn",text:"This content type uses <strong>Layout Builder</strong>. Avoid editing the Layout section."},
          fields:[
            {label:"Title",machine:"title",hint:"Page title shown as the main heading.",status:"required",type:"text"},
            {label:"Description",machine:"field_description",hint:"Short descriptive text.",status:"required",type:"plain-text"},
            {label:"Content",machine:"field_content",hint:"Main body content.",status:"optional",type:"rich-text"},
            {label:"Featured Image",machine:"field_featured_image",hint:"Hero or banner image.",status:"optional",type:"media-image"},
            {label:"Links",machine:"field_links",hint:"Additional links. Multiple allowed.",status:"optional",type:"link",multiple:true},
            {label:"Tags",machine:"field_tags",hint:"Tag for grouping.",status:"optional",type:"taxonomy",multiple:true},
          ]},
        { id:"page_with_links", name:"Page with Links", machine:"page_with_links", group:"Pages & Navigation", icon:"🔗", color:"#FEF9E7",
          description:"A lighter page type for sections that are primarily a curated list of links.",
          fields:[
            {label:"Title",machine:"title",hint:"Page title.",status:"required",type:"text"},
            {label:"Introduction",machine:"field_intro",hint:"Short formatted intro paragraph.",status:"optional",type:"rich-text"},
            {label:"Long Introduction",machine:"field_long_introduction",hint:"More detailed intro if needed.",status:"optional",type:"rich-text"},
            {label:"External Links",machine:"field_links",hint:"The list of links. Multiple allowed.",status:"optional",type:"link",multiple:true},
          ]},
        { id:"about_us", name:"About Us", machine:"about_us", group:"Pages & Navigation", icon:"🏢", color:"#FDE8E8",
          description:"Content for the About Us section pages.",
          fields:[
            {label:"Title",machine:"title",hint:"Section title.",status:"required",type:"text"},
            {label:"Body",machine:"field_body",hint:"Main content.",status:"optional",type:"rich-text"},
            {label:"Image",machine:"field_image",hint:"Supporting image.",status:"optional",type:"media-image"},
          ]},
        { id:"quicklinks", name:"Quicklinks", machine:"quicklinks", group:"Pages & Navigation", icon:"⚡", color:"#E8F7EE",
          description:"External agency or partner links shown in the Quicklinks section.",
          fields:[
            {label:"Agency Name",machine:"title",hint:"Name of the agency.",status:"required",type:"text"},
            {label:"Description",machine:"field_description",hint:"One-line description.",status:"optional",type:"plain-text"},
            {label:"Logo",machine:"field_logo",hint:"Upload the agency logo.",status:"optional",type:"media-image"},
            {label:"Link",machine:"field_links",hint:"URL of the agency website.",status:"optional",type:"link",multiple:true},
            {label:"Quicklink Category",machine:"field_quicklink_category",hint:"Which group this belongs to.",status:"optional",type:"taxonomy"},
            {label:"Topic",machine:"field_topic",hint:"Link to a related page/topic.",status:"optional",type:"content-ref"},
          ]},
        { id:"management_team", name:"Management Team", machine:"management_team", group:"People & Organisation", icon:"👤", color:"#EEF2F7",
          description:"Profiles for senior management and leadership team members.",
          fields:[
            {label:"Full Name",machine:"title",hint:"The person's full name.",status:"required",type:"text"},
            {label:"Profile Picture",machine:"field_profile_picture",hint:"Headshot photo.",status:"optional",type:"media-image"},
            {label:"Position / Title",machine:"field_positions",hint:"Select the job title.",status:"optional",type:"taxonomy"},
            {label:"Division",machine:"field_division",hint:"Select the division.",status:"optional",type:"taxonomy"},
            {label:"Description / Bio",machine:"field_body",hint:"Biography.",status:"optional",type:"rich-text"},
            {label:"Email Address",machine:"field_email_address",hint:"Official email address.",status:"optional",type:"email"},
          ]},
        { id:"energy_commission_members", name:"EC Members", machine:"energy_commission_members", group:"People & Organisation", icon:"🎖️", color:"#FDE8E8",
          description:"Profiles for appointed Energy Commission board members.",
          fields:[
            {label:"Full Name",machine:"title",hint:"The member's full name.",status:"required",type:"text"},
            {label:"Profile Picture",machine:"field_profile_picture",hint:"Headshot photo.",status:"optional",type:"media-image"},
            {label:"Position / Title",machine:"field_positions",hint:"Select the member's role/title.",status:"optional",type:"taxonomy"},
            {label:"Date of Appointment",machine:"field_date_of_appointment",hint:"Official appointment date.",status:"optional",type:"plain-text"},
            {label:"Description / Bio",machine:"field_body",hint:"Biography.",status:"optional",type:"rich-text"},
          ]},
        { id:"staff", name:"Staff", machine:"staff", group:"People & Organisation", icon:"👥", color:"#F0EDE8",
          description:"Staff directory entries for ST employees.",
          fields:[
            {label:"Full Name",machine:"title",hint:"The staff member's full name.",status:"required",type:"text"},
            {label:"Position",machine:"field_positions",hint:"Select from the Positions taxonomy.",status:"optional",type:"taxonomy"},
            {label:"Division",machine:"field_division",hint:"Select the division.",status:"optional",type:"taxonomy"},
            {label:"Section",machine:"field_section",hint:"Select the specific section.",status:"optional",type:"taxonomy"},
            {label:"Email Address",machine:"field_email_address",hint:"Official ST email.",status:"optional",type:"email"},
            {label:"Telephone",machine:"field_telephone",hint:"Direct phone number.",status:"optional",type:"phone"},
          ]},
        { id:"section_contact", name:"Section Contact", machine:"section_contact", group:"People & Organisation", icon:"📧", color:"#E8F7EE",
          description:"Contact information for a specific department or section.",
          fields:[
            {label:"Section Name",machine:"title",hint:"Name of the section or department.",status:"required",type:"text"},
            {label:"Division",machine:"field_division",hint:"Select the division.",status:"optional",type:"taxonomy"},
            {label:"Email Address",machine:"field_email_address",hint:"Contact email.",status:"optional",type:"email"},
          ]},
        { id:"career", name:"Career", machine:"career", group:"Procurement & Licensing", icon:"💼", color:"#FEF9E7",
          description:"Job vacancy and career opportunity postings.",
          fields:[
            {label:"Job Title",machine:"title",hint:"Name of the position.",status:"required",type:"text"},
            {label:"Overview",machine:"field_overview",hint:"Full job description.",status:"optional",type:"rich-text"},
            {label:"Application Period",machine:"field_date_range",hint:"Opening and closing dates.",status:"optional",type:"date-range"},
            {label:"Attachment",machine:"field_file_attachment",hint:"Upload related documents.",status:"optional",type:"media-doc",multiple:true},
          ]},
        { id:"tender_quotation", name:"Tender / Quotation", machine:"tender_quotation", group:"Procurement & Licensing", icon:"📑", color:"#FDE8E8",
          description:"Procurement tender and quotation notices.",
          fields:[
            {label:"Title",machine:"title",hint:"Full name of the tender/quotation.",status:"required",type:"text"},
            {label:"Reference Code",machine:"field_code",hint:"Official reference number.",status:"optional",type:"plain-text"},
            {label:"Type",machine:"field_type",hint:"Select Tender or Quotation.",status:"optional",type:"dropdown"},
            {label:"Submission Period",machine:"field_start_and_end_date",hint:"Opening and closing dates.",status:"optional",type:"date-range"},
            {label:"Notice Date",machine:"field_notice_date",hint:"Date the notice was issued.",status:"optional",type:"date"},
            {label:"Collection Date",machine:"field_collection_date",hint:"Deadline for document collection.",status:"optional",type:"date"},
            {label:"Advertisement Doc",machine:"field_ad_attachment",hint:"Upload the advertisement document.",status:"optional",type:"file"},
            {label:"Notice Document",machine:"field_notice_attachment",hint:"Upload the notice document.",status:"optional",type:"file"},
          ]},
        { id:"public_distribution_licensee", name:"Public Distribution Licensee", machine:"public_distribution_licensee", group:"Procurement & Licensing", icon:"⚡", color:"#EEF2F7",
          description:"Registry entries for licensed public electricity distribution companies.",
          fields:[
            {label:"Licensee Name",machine:"title",hint:"Full legal name of the licensee.",status:"required",type:"text"},
            {label:"Address",machine:"field_licensee_address",hint:"Registered business address.",status:"optional",type:"plain-text"},
            {label:"Capacity (MW)",machine:"field_capacity",hint:"Licensed distribution capacity.",status:"optional",type:"number"},
            {label:"License Start Date",machine:"field_start_date",hint:"Date the license was granted.",status:"optional",type:"date"},
            {label:"License End Date",machine:"field_end_date",hint:"Date the license expires.",status:"optional",type:"date"},
          ]},
        { id:"office_locations", name:"Office Locations", machine:"office_locations", group:"Location", icon:"📍", color:"#FEF9E7",
          description:"ST office and branch contact details.",
          fields:[
            {label:"Office Name",machine:"title",hint:"Name of the office.",status:"required",type:"text"},
            {label:"Address",machine:"field_address",hint:"Full street address.",status:"optional",type:"address"},
            {label:"Telephone",machine:"field_telephone",hint:"Main phone number.",status:"optional",type:"phone"},
            {label:"Fax",machine:"field_fax",hint:"Fax number if applicable.",status:"optional",type:"phone"},
            {label:"Email Address",machine:"field_email_address",hint:"Contact email.",status:"optional",type:"email"},
            {label:"Operating Hours",machine:"field_operating_hours",hint:"e.g. Monday – Friday: 8:00am – 5:00pm.",status:"optional",type:"plain-text"},
            {label:"Office Type",machine:"field_office_type",hint:"Select HQ, Regional, or Branch.",status:"optional",type:"taxonomy"},
            {label:"State",machine:"field_state",hint:"Select the Malaysian state.",status:"optional",type:"taxonomy"},
            {label:"Map Coordinates",machine:"field_lat_long",hint:"Lat/long for the map pin.",status:"optional",type:"geofield"},
          ]},
      ]